//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceDiario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BalanceDiario()
        {
            this.SalidaExtraordinaria = new HashSet<SalidaExtraordinaria>();
        }
    
        public int Id { get; set; }
        public int IdPersonal { get; set; }
        public System.DateTime TiempoInicio { get; set; }
        public System.DateTime TiempoFinal { get; set; }
        public double TotalSalidaCalculado { get; set; }
        public double TotalEntradaClaculado { get; set; }
        public int SalidaDeCaja { get; set; }
        public int EntradaDeCaja { get; set; }
        public double Ganancia { get; set; }
        public double CantidadEnCaja { get; set; }
    
        public virtual CajaEntrada CajaEntrada { get; set; }
        public virtual CajaSalida CajaSalida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalidaExtraordinaria> SalidaExtraordinaria { get; set; }
    }
}
