//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    
    public partial class EIngrediente
    {
        public int CodigoInsumo { get; set; }
        public string NombreInsumo { get; set; }
        public double CantidadIngrediente { get; set; }
        public double CantidadInsumo { get; set; }
        public string Unidad { get; set; }
        public double PrecioInsumo { get; set; }
    }
}
