//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    
    public partial class EInsumo
    {
        public int Codigo { get; set; }
        public double PrecioCompra { get; set; }
        public double Cantidad { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Restricciones { get; set; }
        public string Status { get; set; }
        public System.DateTime Registro { get; set; }
        public string UnidadMedida { get; set; }
        public string ProveedorDeInsumo { get; set; }
    }
}
