//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Empleado_Direccion = new HashSet<Empleado_Direccion>();
        }
    
        public int Clave { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string TipoUsuario { get; set; }
        public Nullable<int> CodigoPostal { get; set; }
        public string Status { get; set; }
        public string Puesto { get; set; }
        public Nullable<double> Salario { get; set; }
        public string Telefono { get; set; }
        public string Ciudad { get; set; }
        public System.DateTime Registro { get; set; }
        public Nullable<System.DateTime> Baja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado_Direccion> Empleado_Direccion { get; set; }
    }
}
