//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    
    public partial class EPedidoClienteDetallado
    {
        public int Codigo { get; set; }
        public double CostoTotal { get; set; }
        public string StatusPedido { get; set; }
        public System.DateTime Solicitud { get; set; }
        public Nullable<System.DateTime> Entrega { get; set; }
        public double Cantidad { get; set; }
        public string TipoPedido { get; set; }
        public Nullable<int> IdClientePedido { get; set; }
        public Nullable<int> IdDireccion { get; set; }
        public string MotivoCancelacion { get; set; }
        public Nullable<int> IdClientePropio { get; set; }
        public string Email { get; set; }
        public Nullable<int> CodigoPostal { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string StatusCliente { get; set; }
        public string Telefono { get; set; }
        public string Ciudad { get; set; }
        public Nullable<System.DateTime> Nacimiento { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string Calle { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Colonia { get; set; }
    }
}
