//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Collections.Generic;

    public partial class EPedidoProveedor
    {
        public int Codigo { get; set; }
        public int ClaveProveedor { get; set; }
        public double Cantidad { get; set; }
        public string TipoPedido { get; set; }
        public string Status { get; set; }
        public List<EInsumoPedido> Insumos { get; set; }    
    }
}
