//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingrediente
    {
        public int ClaveReceta { get; set; }
        public int CodigoInsumo { get; set; }
        public double Cantidad { get; set; }
    
        public virtual Insumo Insumo { get; set; }
        public virtual Receta Receta { get; set; }
    }
}
