//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredientes
    {
        public int ClaveReceta { get; set; }
        public int CodigoProducto { get; set; }
        public int CantidadProducto { get; set; }
        public string NombreProducto { get; set; }
        public int CodigoInsumo { get; set; }
        public double CantidadIngrediente { get; set; }
        public string NombreInsumo { get; set; }
        public double CantidadInsumo { get; set; }
        public string StatusInsumo { get; set; }
        public double PrecioInsumo { get; set; }
        public string Unidad { get; set; }
    }
}
