//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insumo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insumo()
        {
            this.Ingrediente = new HashSet<Ingrediente>();
            this.OrdenAProveedor = new HashSet<OrdenAProveedor>();
        }
    
        public int Codigo { get; set; }
        public double PrecioCompra { get; set; }
        public double Cantidad { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Restricciones { get; set; }
        public string Status { get; set; }
        public System.DateTime Registro { get; set; }
        public string UnidadMedida { get; set; }
        public string ProveedorDeInsumo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingrediente> Ingrediente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenAProveedor> OrdenAProveedor { get; set; }
    }
}
