//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        public int CodigoPedido { get; set; }
        public int CodigoProductoVenta { get; set; }
        public int Cantidad { get; set; }
        public double Precio { get; set; }
    
        public virtual PedidoCliente PedidoCliente { get; set; }
        public virtual ProductoVenta ProductoVenta { get; set; }
    }
}
