//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int Codigo { get; set; }
        public double CostoTotal { get; set; }
        public string Status { get; set; }
        public System.DateTime Solicitud { get; set; }
        public Nullable<System.DateTime> Entrega { get; set; }
        public double Cantidad { get; set; }
        public string TipoPedido { get; set; }
        public Nullable<int> NumeroProductos { get; set; }
    }
}
