//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int Codigo { get; set; }
        public double CostoTotal { get; set; }
        public string Status { get; set; }
        public System.DateTime Solicitud { get; set; }
        public Nullable<System.DateTime> Entrega { get; set; }
    
        public virtual PedidoProveedor PedidoProveedor { get; set; }
        public virtual PedidoCliente PedidoCliente { get; set; }
    }
}
