//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosDomicilio
    {
        public int CodigoPedido { get; set; }
        public double CostoTotal { get; set; }
        public string StatusPedido { get; set; }
        public System.DateTime Solicitud { get; set; }
        public Nullable<System.DateTime> Entrega { get; set; }
        public int Id { get; set; }
        public string Email { get; set; }
        public int CodigoPostal { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Status { get; set; }
        public string Telefono { get; set; }
        public string Ciudad { get; set; }
        public System.DateTime Nacimiento { get; set; }
        public int Edad { get; set; }
        public int Codigo { get; set; }
        public double Cantidad { get; set; }
        public string TipoPedido { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdDireccion { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<int> NumeroProductos { get; set; }
    }
}
