//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalidaExtraordinaria
    {
        public int Id { get; set; }
        public int IdBalance { get; set; }
        public string Descripcion { get; set; }
        public string UsuarioRegistrador { get; set; }
        public double Importe { get; set; }
        public System.DateTime Registro { get; set; }
    
        public virtual BalanceDiario BalanceDiario { get; set; }
    }
}
