//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalidaExtraordinaria
    {
        public int Id { get; set; }
        public int IdBalance { get; set; }
        public string Descripcion { get; set; }
        public string UsuarioRegistrador { get; set; }
        public double Importe { get; set; }
        public System.DateTime Registro { get; set; }
    
        public virtual BalanceDiario BalanceDiario { get; set; }
    }
}
